{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: service-route
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: {{ .Values.gateway.name }}
  hostnames:
  {{- if .Values.hosts.usePaths }}
  - {{ tpl (.Values.hosts.configuration.baseHost | toString) . }}
  {{- else }}
  - {{ printf "%s.%s" (tpl .Values.hosts.configuration.service .) (tpl .Values.hosts.configuration.baseHost .) }}
  {{- end }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        {{- if .Values.hosts.usePaths }}
        value: /{{ tpl (.Values.hosts.configuration.service | toString) . }}/service
        {{- else }}
        value: /service
        {{- end }}
    filters:
    {{- if .Values.hosts.usePaths }}
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /service
    {{- end }}
    backendRefs:
    - name: service-service
      port: {{ tpl (.Values.service.port | toString) . }}
{{- end }}
