{{- if .Values.landingPage.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: landing-page-config
  namespace: {{ .Release.Namespace }}
data:
  config.js: |
    window.theiaCloudConfig = {
      serviceAuthToken: "{{ tpl ((.Values.service.authToken | default .Values.app.id) | toString) . }}",
      appName: "{{ tpl (.Values.app.name | toString) . }}",
      useEphemeralStorage: {{ tpl (.Values.landingPage.ephemeralStorage | toString) . }},
      useKeycloak: {{ tpl (.Values.keycloak.enable | toString) . }},
      keycloakAuthUrl: "{{ tpl (.Values.keycloak.authUrl | toString) . }}",
      keycloakRealm: "{{ tpl (.Values.keycloak.realm | toString) . }}",
      keycloakClientId: "{{ tpl (.Values.keycloak.clientId | toString) . }}",
      {{- if .Values.hosts.usePaths }}
      serviceUrl: "{{ tpl (.Values.service.protocol | toString) . }}://{{ tpl (.Values.hosts.configuration.baseHost | toString) . }}/{{ tpl (.Values.hosts.configuration.service | toString) . }}",
      {{- else }}
      serviceUrl: "{{ tpl (.Values.service.protocol | toString) . }}://{{ tpl (.Values.hosts.configuration.service | toString) . }}.{{ tpl (.Values.hosts.configuration.baseHost | toString) . }}",
      {{- end }}
      appDefinition: "{{ tpl (.Values.landingPage.appDefinition | toString) . }}",
      additionalApps: [
        {{- range $key, $val := .Values.landingPage.additionalApps }}
        {
          serviceAuthToken: {{ $key | quote}},
          appName: {{ $val.label | quote }},
        },
        {{- end }}
      ],
      // We force PNG because we are forcing logo.png in the deployment
      logoFileExtension: "png",
      disableInfo: {{ tpl (.Values.landingPage.disableInfo | toString) . }},
      {{- if .Values.landingPage.infoText }}
      infoText: "{{ tpl (.Values.landingPage.infoText | toString) . }}",
      {{- end }}
      {{- if .Values.landingPage.infoTitle }}
      infoTitle: "{{ tpl (.Values.landingPage.infoTitle | toString) . }}",
      {{- end }}
      {{- if .Values.landingPage.loadingText }}
      loadingText: "{{ tpl (.Values.landingPage.loadingText | toString) . }}",
      {{- end }}
      {{- if .Values.landingPage.footerLinks }}
      footerLinks: {
        {{- if .Values.landingPage.footerLinks.attribution }}
        attribution: {
          {{- if .Values.landingPage.footerLinks.attribution.text }}
          text: "{{ tpl (.Values.landingPage.footerLinks.attribution.text | toString) . }}",
          {{- end }}
          {{- if .Values.landingPage.footerLinks.attribution.url }}
          url: "{{ tpl (.Values.landingPage.footerLinks.attribution.url | toString) . }}",
          {{- end }}
          {{- if .Values.landingPage.footerLinks.attribution.version }}
          version: "{{ tpl (.Values.landingPage.footerLinks.attribution.version | toString) . }}",
          {{- end }}
        },
        {{- end }}
        {{- if .Values.landingPage.footerLinks.bugReport }}
        bugReport: {
          {{- if .Values.landingPage.footerLinks.bugReport.text }}
          text: "{{ tpl (.Values.landingPage.footerLinks.bugReport.text | toString) . }}",
          {{- end }}
          {{- if .Values.landingPage.footerLinks.bugReport.url }}
          url: "{{ tpl (.Values.landingPage.footerLinks.bugReport.url | toString) . }}",
          {{- end }}
          {{- if .Values.landingPage.footerLinks.bugReport.target }}
          target: "{{ tpl (.Values.landingPage.footerLinks.bugReport.target | toString) . }}",
          {{- end }}
          {{- if .Values.landingPage.footerLinks.bugReport.rel }}
          rel: "{{ tpl (.Values.landingPage.footerLinks.bugReport.rel | toString) . }}",
          {{- end }}
        },
        {{- end }}
        {{- if .Values.landingPage.footerLinks.featureRequest }}
        featureRequest: {
          {{- if .Values.landingPage.footerLinks.featureRequest.text }}
          text: "{{ tpl (.Values.landingPage.footerLinks.featureRequest.text | toString) . }}",
          {{- end }}
          {{- if .Values.landingPage.footerLinks.featureRequest.url }}
          url: "{{ tpl (.Values.landingPage.footerLinks.featureRequest.url | toString) . }}",
          {{- end }}
          {{- if .Values.landingPage.footerLinks.featureRequest.target }}
          target: "{{ tpl (.Values.landingPage.footerLinks.featureRequest.target | toString) . }}",
          {{- end }}
          {{- if .Values.landingPage.footerLinks.featureRequest.rel }}
          rel: "{{ tpl (.Values.landingPage.footerLinks.featureRequest.rel | toString) . }}",
          {{- end }}
        },
        {{- end }}
        {{- if .Values.landingPage.footerLinks.about }}
        about: {
          {{- if .Values.landingPage.footerLinks.about.text }}
          text: "{{ tpl (.Values.landingPage.footerLinks.about.text | toString) . }}",
          {{- end }}
          {{- if .Values.landingPage.footerLinks.about.url }}
          url: "{{ tpl (.Values.landingPage.footerLinks.about.url | toString) . }}",
          {{- end }}
          {{- if .Values.landingPage.footerLinks.about.target }}
          target: "{{ tpl (.Values.landingPage.footerLinks.about.target | toString) . }}",
          {{- end }}
          {{- if .Values.landingPage.footerLinks.about.rel }}
          rel: "{{ tpl (.Values.landingPage.footerLinks.about.rel | toString) . }}",
          {{- end }}
        },
        {{- end }}
      },
      {{- end }}
      sentryEnvironment: "{{ .Release.Namespace }}",
    };

  {{- if .Values.landingPage.logoData }}
  logo.png: {{ .Values.landingPage.logoData }}
  {{- end }}
{{- end }}
