{{- if and .Values.gateway.enabled .Values.gateway.create }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
  {{- if .Values.gateway.tls }}
  - name: https-instances
    protocol: HTTPS
    port: {{ .Values.gateway.httpsPort }}
    hostname: {{ include "theia-cloud.host.instance" . }}
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: ws-cert-secret
  - name: https-service
    protocol: HTTPS
    port: {{ .Values.gateway.httpsPort }}
    hostname: {{ include "theia-cloud.host.service" . }}
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: service-cert-secret
  {{- if .Values.landingPage.enabled }}
  - name: https-landing
    protocol: HTTPS
    port: {{ .Values.gateway.httpsPort }}
    hostname: {{ include "theia-cloud.host.landing" . }}
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: landing-page-cert-secret
  {{- end }}
  {{- range $wildcard := .Values.hosts.allWildcardInstances }}
  - name: {{ include "theia-cloud.gateway.wildcardListenerName" (dict "wildcard" $wildcard) }}
    protocol: HTTPS
    port: {{ $.Values.gateway.httpsPort }}
    hostname: {{ printf "%s%s" (tpl $wildcard $) (include "theia-cloud.host.instance" $) | quote }}
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: {{ if hasKey $.Values.gateway.instancesWildcardSecretNames $wildcard }}{{ tpl (get $.Values.gateway.instancesWildcardSecretNames $wildcard) $ | quote }}{{ else }}ws-cert-secret{{ end }}
  {{- end }}
  {{- end }}
  {{- if .Values.gateway.httpEnabled }}
  - name: http
    protocol: HTTP
    port: {{ .Values.gateway.httpPort }}
  {{- end }}
{{- end }}
