{{- if and .Values.gateway.enabled .Values.gateway.routes.enabled .Values.landingPage.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: landing-route
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
{{ include "theia-cloud.gateway.parentRefs" . | nindent 2 }}
  hostnames:
  - {{ include "theia-cloud.host.landing" . | quote }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: landing-page-service
      port: 80
{{- end }}
